### ISSUE TITLE
Pel que calgui

### ISSUE THREAD

**Issue by IsmaelMartinez** [s3rrallonga/s3rrallonga.github.io#3]
No visc a Catalunya pero soc català, informàtic i contribueixo una mica a OpenSource (quan la vida em deixa). Si puc ajudar en alguna cosa, digueu-me.

Així inicialment crec que necessiteu les 4 coses bàsiques. Utilitzo anglès que porto massa temps visquen a Escocia.

Templates per issues y Bugs
Code of conduct
License
Contributing guideline's.

Quan allibereu el codi, els polis ho miraran amb lupa, però és la única manera de assegurar que la app és segur. 

Salud y ànims!

**Comment by s3rrallonga** [comment]
merci @IsmaelMartinez :)

**Comment by Rabosa616** [comment]
Igualment, per a programar el que us faci falta!

**Comment by joanmarcriera** [comment]
El que faci falta desde UK.

**Comment by IsmaelMartinez** [comment]
Tema license, normalment recomano mirar aquesta web:

**Comment by IsmaelMartinez** [comment]
Tema code of conduct es casi millor fer-ho desde la pagina de "settings" de github. https://help.github.com/en/articles/adding-a-code-of-conduct-to-your-project

**Comment by IsmaelMartinez** [comment]
Tema templates... aqui hi han molts examples:
https://github.com/devspace/awesome-github-templates
else standard de github funcionan pero poden facilitar-hos la feina.

**Comment by DavidBernal** [comment]
El que faci falta!

**Comment by Ryozuki** [comment]
Perquè no fem una org amb projectes on tots hi podem participar.

Hem de guanyar la guerra digital també.

**Comment by Ryozuki** [comment]
He obert una organització, interessats, obriu un issue a la repo "discussio"

https://github.com/RevoltaCatalana

**Comment by oriolpiera** [comment]
Un altre que agafa lloc aquí, pel que calgui.

**Comment by sergivb01** [comment]
Un altre, pel que calgui

**Comment by DavidFD005** [comment]
El mateix dic @s3rrallonga soc dev d’Android i de Flutter, he vist que la app esta feta en flutter. Pel que calgui

**Comment by victorfmin66** [comment]
Un altre aqui! Pel que calgui

**Comment by joanotpetitot** [comment]
Si us cal un timbaler de vora el Bruc amb coneixements de xarxes, cloud, arquitectura de software i seguretat podeu buscar, o si cal, enviarme un pm o postal a thelittletux87 a can protonmail punt com, que segur me la fa arribar el carter del barri rapid.

**Comment by t4llaferro** [comment]
Pel que calgui, també

**Comment by espinacs** [comment]
A disposar.

**Comment by Antartich** [comment]
Pel que calgui  
webDev - Xarxes - Seguretat 
em trobeu com antartich a protonmail
